name: Build and Deploy .NET to Vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'

    - name: Publish Blazor app
      run: |
        dotnet publish BlazorVercel/BlazorVercel.csproj -c Release -o ./temp-publish

        mkdir -p .vercel/output/static

        # Ensure there are files to copy, then copy them safely
        if [ -d "./temp-publish/wwwroot" ]; then
            cp -r ./temp-publish/wwwroot/. .vercel/output/static/
        else
            echo "ERROR: ./temp-publish/wwwroot does not exist"
            exit 1
        fi

        # Write Vercel config
        cat <<EOF > .vercel/output/config.json
        {
            "version": 3,
            "routes": [
                { "src": "/(.*)", "dest": "/index.html" }
        ]
        }
        EOF


    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: |
        vercel deploy --prebuilt --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
      #working-directory: ./publish/wwwroot
