name: Build and Deploy .NET to Vercel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'  # or your required version

    - name: Publish .NET app
      run: dotnet publish BlazorVercel/BlazorVercel.csproj -c Release -o ./publish

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: |
        vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
      working-directory: ./publish/wwwroot
